import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = {
  en: {
    label: 'English',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    settings: 'Settings',
    emailNotifs: 'Email Notifications',
    sosSound: 'SOS Alerts Sound',
    darkMode: 'Dark Mode',
    language: 'Language',
    version: 'SCIA Admin v1.0.0',
    profile: 'Profile Information',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    position: 'Position / Title',
    saveProfile: 'Save Profile',
    saving: 'Saving...',
    saved: 'Saved!',
    changePassword: 'Change Password',
    currentPass: 'Current Password',
    newPass: 'New Password',
    updatePassword: 'Update Password',
    updating: 'Updating...',
    passwordUpdated: 'Password Updated!',
    emailCannotChange: 'Email cannot be changed here.',
    superAdmin: 'OSCA Admin',
    subAdmin: 'Barangay Admin',
    welcomeBack: 'Welcome back',
    editProfile: 'Edit profile',
    // Sidebar
    dashboard: 'Dashboard',
    announcements: 'Announcements',
    eventCheckIn: 'Event Check-In',
    sosMap: 'SOS Map',
    healthCenters: 'Health Centers',
    idManagement: 'ID Management',
    digitalId: 'Digital ID',
    userManagement: 'User Management',
    analytics: 'Analytics',
    generateReport: 'Generate Report',
    signOut: 'Sign Out',
    oscaPlatform: 'OSCA Platform',
    barangayPlatform: 'Barangay Platform',

    // Shared actions / labels
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    reject: 'Reject',
    approve: 'Approve',
    view: 'View',
    viewId: 'View ID',
    downloadPrintId: 'Download / Print ID',
    noResultsFound: 'No results found',
    reviewAction: 'Review',
    dobLabel: 'DOB',
    barangayLabel: 'Barangay',
    sexLabel: 'Sex',
    reasonLabel: 'Reason',
    notSpecified: 'Not specified',
    missing: 'Missing',

    // ID Management page
    idMgmtSubtitle: 'Review and manage senior citizen ID verifications and releases',
    tabIdVerification: 'ID Verification',
    tabIdRelease: 'ID Release',
    tabOscaSubmissions: 'OSCA ID Submissions',
    tabPhysicalRequests: 'Physical ID Requests',
    tabIdRequests: 'ID Requests',
    tabApproved: 'Approved',
    tabReleased: 'Released',
    tabMyReleasedIds: 'My Released IDs',
    statPendingReview: 'Pending Review',
    statApproved: 'Approved',
    statRejected: 'Rejected',
    statTotalSubmitted: 'Total Submitted',
    statPending: 'Pending',
    statVoidIncomplete: 'Void/Incomplete',
    statPendingRequests: 'Pending Requests',
    statReleasedCount: 'Released',
    statVoidIncomplete2: 'Void / Incomplete',
    statAwaitingPickup: 'Awaiting Pickup',
    statCollected: 'Collected',
    statTotalReleased: 'Total Released',
    reviewedSection: 'Reviewed',
    noVerificationYet: 'No verification requests yet',
    noPhysicalReqsYet: 'No physical ID requests yet',
    multipleReqsWarning: 'user(s) submitted multiple requests — highlighted in orange.',
    voidReqsWarning: 'request(s) are void — incomplete profile.',
    searchByNameOrOsca: 'Search by name or OSCA ID…',
    deleteRequestTitle: 'Delete Request?',
    deleteRequestBody1: 'You are about to delete the request from',
    deleteRequestWarning: 'This will permanently remove the record from the system.',
    oscaVerifTitle: 'OSCA ID Verification',
    oscaVerifSubtitle: 'Review the submitted ID photo and details below.',
    oscaIdOnCard: 'OSCA ID on card',
    submittedLabel: 'Submitted',
    uploadedIdPhoto: 'Uploaded OSCA ID Photo',
    noIdImageUploaded: 'No ID image uploaded',
    approveVerifyNote: "Approving will verify the senior's account and queue a physical ID for release. Their digital ID can then be released from the Digital ID page.",
    approveVerify: 'Approve & Verify',
    physicalIdReqTitle: 'Physical ID Request',
    reviewReqDetails: 'Review the request details below.',
    idCardPreview: 'ID Card Preview',
    requiredInfoCheck: 'Required Information Check',
    cannotRelease: 'Cannot release',
    birthdayNotOnRecordRelease: "birthday is not on record. Please update the senior's birthday before releasing the ID.",
    birthdayNotOnRecordPill: 'Birthday not on record',
    cannotReleaseIncomplete: "Cannot release — required information is incomplete. Please update the senior's record first.",
    confirmReleaseCheckbox: 'I confirm that all information on this physical ID is correct and complete. This ID will be sent to the assigned sub-admin for barangay distribution.',
    releaseToSubAdmin: 'Release to Sub-Admin',
    reviewVerifyBeforeApproving: 'Review and verify before approving',
    cannotApprove: 'Cannot approve',
    birthdayNotOnRecordApprove: "birthday not on record. Update the senior's birthday first.",
    requestedLabel: 'Requested',
    approveRequest: 'Approve Request',
    birthdayRequired: 'Birthday required',
    unknownLabel: 'Unknown',
    oscaIdPrefix: 'OSCA ID',
    deleteRequestFor: 'deleted.',
    pendingRequestsSection: 'Pending Requests',
    noPendingIdRequests: 'No pending ID requests',
    voidSignupWarning: 'request(s) are void — user did not complete sign-up.',
    rejectedSection: 'Rejected',
    clickReleaseNote: 'Click "Release" to do a final verification of the ID card before sending to the sub-admin.',
    noApprovedAwaitingRelease: 'No approved IDs awaiting release',
    noIdsReleasedYet: 'No IDs released yet',
    readyForPickupPrefix: 'You have',
    readyForPickupSuffix: 'physical ID(s) ready for distribution in your barangay.',
    markCollected: 'Mark Collected',
    noIdsAssignedYet: 'No IDs assigned to your barangay yet',
    superAdminWillRelease: "Super admin will release IDs to you when they're ready",
    releaseLabel: 'Release',
    releasePhysicalId: 'Release Physical ID',
    finalVerificationSubtitle: 'Final verification before releasing to sub-admin',
    dateOfBirthCheck: 'Date of Birth',
    addressCheck: 'Address',
    oscaIdControlNoCheck: 'OSCA ID / Control No.',
    barangayAssignmentCheck: 'Barangay Assignment',
    toastApprovedQueued: 'Approved! Senior verified and physical ID queued for release.',
    toastRequestRejected: 'Request rejected.',
    toastRequestForPrefix: 'Request for',
    toastRequestForSuffix: 'approved.',
    toastMarkedCollected: 'Marked as collected.',
    toastPhysicalIdReleasedPrefix: 'Physical ID for',
    toastPhysicalIdReleasedSuffix: 'released to sub-admin.',
    filterAll: 'All',
    filterPending: 'Pending',
    filterApproved: 'Approved',
    filterRejected: 'Rejected',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    statusVerified: 'Verified',
    statusReleased: 'Released',
    statusNotified: 'Notified',
    statusCollected: 'Collected',
    statusVoid: 'Void',
    repeatBadge: 'REPEAT',
    voidBadge: 'VOID',
    noBirthdayBadge: 'NO BIRTHDAY',

    // Digital ID page
    digitalIdsTitle: 'Digital IDs',
    digitalIdsSubtitle: 'View all issued digital OSCA IDs · Verify registration status · Invalidate if not actually registered',
    hideTemplate: 'Hide ID Card Template Design',
    viewTemplate: 'View ID Card Template Design',
    blankSample: '(blank sample)',
    sampleDesignNoData: 'Sample Design — No Personal Data',
    clickToFlip: 'Click the card to flip and see benefits layout',
    templateNote: "This is the official OSCA Valenzuela digital ID template with real logos. Actual IDs will display the senior's personal information.",
    digitalIdPreview: 'Digital ID Preview',
    invalidateThisId: 'Invalidate This ID',
    statActiveIds: 'Active IDs',
    statInvalidated: 'Invalidated',
    statTotalIssued: 'Total Issued',
    readyForReleaseSection: 'Verified Seniors, Ready for Digital ID Release',
    noSeniorsReady: 'No verified seniors waiting on a digital ID right now.',
    verifiedLabel: 'Verified',
    releaseDigitalId: 'Release Digital ID',
    searchByNameOrControl: 'Search by name or control number…',
    activeDigitalIds: 'Active Digital IDs',
    invalidatedIds: 'Invalidated IDs',
    ctrlNo: 'Ctrl No.',
    releasedLabel: 'Released',
    invalidatedLabel: 'Invalidated',
    noDigitalIdsYet: 'No digital IDs issued yet',
    digitalIdNoLinkedAccount: 'This record has no linked account, cannot release.',
    digitalIdReleasedFor: 'Digital ID released for',
    digitalIdReleaseFailed: 'Failed to release digital ID. Please try again.',
    invalidateConfirm: 'Invalidate digital ID for',
    invalidateConfirmSuffix: 'This will mark it as revoked.',
    digitalIdInvalidatedFor: 'Digital ID for',
    digitalIdInvalidatedSuffix: 'has been invalidated.',
  },
  fil: {
    label: 'Filipino',
    notifications: 'Mga Abiso',
    noNotifications: 'Walang abiso',
    settings: 'Mga Setting',
    emailNotifs: 'Mga Abiso sa Email',
    sosSound: 'Tunog ng SOS Alerto',
    darkMode: 'Madilim na Mode',
    language: 'Wika',
    version: 'SCIA Admin v1.0.0',
    profile: 'Impormasyon ng Profile',
    fullName: 'Buong Pangalan',
    email: 'Email',
    phone: 'Telepono',
    position: 'Posisyon / Titulo',
    saveProfile: 'I-save ang Profile',
    saving: 'Sine-save...',
    saved: 'Na-save!',
    changePassword: 'Baguhin ang Password',
    currentPass: 'Kasalukuyang Password',
    newPass: 'Bagong Password',
    updatePassword: 'I-update ang Password',
    updating: 'Ina-update...',
    passwordUpdated: 'Na-update ang Password!',
    emailCannotChange: 'Hindi mababago ang email dito.',
    superAdmin: 'OSCA Admin',
    subAdmin: 'Barangay Admin',
    welcomeBack: 'Maligayang pagbabalik',
    editProfile: 'I-edit ang profile',
    dashboard: 'Dashboard',
    announcements: 'Mga Anunsyo',
    eventCheckIn: 'Pag-check-in sa Event',
    sosMap: 'Mapa ng SOS',
    healthCenters: 'Mga Health Center',
    idManagement: 'Pamamahala ng ID',
    digitalId: 'Digital ID',
    userManagement: 'Pamamahala ng User',
    analytics: 'Analytics',
    generateReport: 'Gumawa ng Ulat',
    signOut: 'Mag-sign Out',
    oscaPlatform: 'OSCA Platform',
    barangayPlatform: 'Barangay Platform',

    // Shared actions / labels
    cancel: 'Kanselahin',
    close: 'Isara',
    delete: 'Burahin',
    reject: 'Tanggihan',
    approve: 'Aprubahan',
    view: 'Tingnan',
    viewId: 'Tingnan ang ID',
    downloadPrintId: 'I-download / I-print ang ID',
    noResultsFound: 'Walang nahanap na resulta',
    reviewAction: 'Suriin',
    dobLabel: 'Kapanganakan',
    barangayLabel: 'Barangay',
    sexLabel: 'Kasarian',
    reasonLabel: 'Dahilan',
    notSpecified: 'Hindi tinukoy',
    missing: 'Kulang',

    // ID Management page
    idMgmtSubtitle: 'Suriin at pamahalaan ang mga pag-verify at paglabas ng ID ng mga senior citizen',
    tabIdVerification: 'Pag-verify ng ID',
    tabIdRelease: 'Paglabas ng ID',
    tabOscaSubmissions: 'Mga Isinumiteng OSCA ID',
    tabPhysicalRequests: 'Mga Kahilingan ng Pisikal na ID',
    tabIdRequests: 'Mga Kahilingan ng ID',
    tabApproved: 'Aprubado',
    tabReleased: 'Nailabas na',
    tabMyReleasedIds: 'Aking mga Nailabas na ID',
    statPendingReview: 'Naghihintay ng Review',
    statApproved: 'Aprubado',
    statRejected: 'Tinanggihan',
    statTotalSubmitted: 'Kabuuang Isinumite',
    statPending: 'Naghihintay',
    statVoidIncomplete: 'Walang-bisa/Hindi Kumpleto',
    statPendingRequests: 'Naghihintay na Kahilingan',
    statReleasedCount: 'Nailabas',
    statVoidIncomplete2: 'Walang-bisa / Hindi Kumpleto',
    statAwaitingPickup: 'Naghihintay ng Pickup',
    statCollected: 'Nakuha na',
    statTotalReleased: 'Kabuuang Nailabas',
    reviewedSection: 'Nasuri na',
    noVerificationYet: 'Wala pang mga kahilingan sa pag-verify',
    noPhysicalReqsYet: 'Wala pang mga kahilingan ng pisikal na ID',
    multipleReqsWarning: 'user na nagsumite ng maraming kahilingan — naka-highlight sa orange.',
    voidReqsWarning: 'kahilingan ang walang-bisa — hindi kumpletong profile.',
    searchByNameOrOsca: 'Maghanap gamit ang pangalan o OSCA ID…',
    deleteRequestTitle: 'Burahin ang Kahilingan?',
    deleteRequestBody1: 'Ibubura mo na ang kahilingan mula kay',
    deleteRequestWarning: 'Permanenteng aalisin nito ang record mula sa system.',
    oscaVerifTitle: 'Pag-verify ng OSCA ID',
    oscaVerifSubtitle: 'Suriin ang isinumiteng larawan ng ID at mga detalye sa ibaba.',
    oscaIdOnCard: 'OSCA ID sa card',
    submittedLabel: 'Isinumite',
    uploadedIdPhoto: 'Na-upload na Larawan ng OSCA ID',
    noIdImageUploaded: 'Walang na-upload na larawan ng ID',
    approveVerifyNote: 'Ang pag-apruba ay magve-verify sa account ng senior at maglalagay ng pisikal na ID sa pila para ilabas. Maaari nang ilabas ang kanilang digital ID mula sa Digital ID page.',
    approveVerify: 'Aprubahan at I-verify',
    physicalIdReqTitle: 'Kahilingan ng Pisikal na ID',
    reviewReqDetails: 'Suriin ang mga detalye ng kahilingan sa ibaba.',
    idCardPreview: 'Preview ng ID Card',
    requiredInfoCheck: 'Pagsusuri ng Kailangang Impormasyon',
    cannotRelease: 'Hindi maaaring ilabas',
    birthdayNotOnRecordRelease: 'hindi nakatala ang kaarawan. Paki-update muna ang kaarawan ng senior bago ilabas ang ID.',
    birthdayNotOnRecordPill: 'Hindi nakatala ang kaarawan',
    cannotReleaseIncomplete: 'Hindi maaaring ilabas — hindi kumpleto ang kailangang impormasyon. Paki-update muna ang record ng senior.',
    confirmReleaseCheckbox: 'Kinukumpirma ko na tama at kumpleto ang lahat ng impormasyon sa pisikal na ID na ito. Ipapadala ang ID na ito sa itinalagang sub-admin para sa pamamahagi sa barangay.',
    releaseToSubAdmin: 'Ilabas sa Sub-Admin',
    reviewVerifyBeforeApproving: 'Suriin at i-verify bago aprubahan',
    cannotApprove: 'Hindi maaaring aprubahan',
    birthdayNotOnRecordApprove: 'hindi nakatala ang kaarawan. I-update muna ang kaarawan ng senior.',
    requestedLabel: 'Hiniling',
    approveRequest: 'Aprubahan ang Kahilingan',
    birthdayRequired: 'Kailangan ang kaarawan',
    unknownLabel: 'Hindi kilala',
    oscaIdPrefix: 'OSCA ID',
    deleteRequestFor: 'nabura.',
    pendingRequestsSection: 'Naghihintay na mga Kahilingan',
    noPendingIdRequests: 'Walang naghihintay na kahilingan ng ID',
    voidSignupWarning: 'kahilingan ang walang-bisa — hindi natapos ng user ang pag-sign up.',
    rejectedSection: 'Tinanggihan',
    clickReleaseNote: 'I-click ang "Ilabas" para sa huling pagsusuri ng ID card bago ipadala sa sub-admin.',
    noApprovedAwaitingRelease: 'Walang aprubadong ID na naghihintay ilabas',
    noIdsReleasedYet: 'Wala pang nailabas na ID',
    readyForPickupPrefix: 'Mayroon kang',
    readyForPickupSuffix: 'pisikal na ID na handa nang ipamahagi sa inyong barangay.',
    markCollected: 'Markahang Nakuha na',
    noIdsAssignedYet: 'Wala pang ID na naitalaga sa inyong barangay',
    superAdminWillRelease: 'Ilalabas ng super admin ang mga ID sa inyo kapag handa na ang mga ito',
    releaseLabel: 'Ilabas',
    releasePhysicalId: 'Ilabas ang Pisikal na ID',
    finalVerificationSubtitle: 'Huling pagpapatunay bago ilabas sa sub-admin',
    dateOfBirthCheck: 'Petsa ng Kapanganakan',
    addressCheck: 'Address',
    oscaIdControlNoCheck: 'OSCA ID / Control No.',
    barangayAssignmentCheck: 'Itinalagang Barangay',
    toastApprovedQueued: 'Aprubado! Na-verify ang senior at nakapila na ang pisikal na ID para ilabas.',
    toastRequestRejected: 'Tinanggihan ang kahilingan.',
    toastRequestForPrefix: 'Kahilingan para kay',
    toastRequestForSuffix: 'aprubado.',
    toastMarkedCollected: 'Namarkahang nakuha na.',
    toastPhysicalIdReleasedPrefix: 'Pisikal na ID para kay',
    toastPhysicalIdReleasedSuffix: 'nailabas sa sub-admin.',
    filterAll: 'Lahat',
    filterPending: 'Naghihintay',
    filterApproved: 'Aprubado',
    filterRejected: 'Tinanggihan',
    statusPending: 'Naghihintay',
    statusApproved: 'Aprubado',
    statusRejected: 'Tinanggihan',
    statusVerified: 'Na-verify',
    statusReleased: 'Nailabas',
    statusNotified: 'Naabisuhan',
    statusCollected: 'Nakuha na',
    statusVoid: 'Walang-bisa',
    repeatBadge: 'ULIT',
    voidBadge: 'WALANG-BISA',
    noBirthdayBadge: 'WALANG KAARAWAN',

    // Digital ID page
    digitalIdsTitle: 'Mga Digital ID',
    digitalIdsSubtitle: 'Tingnan ang lahat ng inilabas na digital OSCA ID · I-verify ang status ng rehistrasyon · I-invalidate kung hindi talaga rehistrado',
    hideTemplate: 'Itago ang Disenyo ng ID Card Template',
    viewTemplate: 'Tingnan ang Disenyo ng ID Card Template',
    blankSample: '(blangkong sample)',
    sampleDesignNoData: 'Sample na Disenyo — Walang Personal na Datos',
    clickToFlip: 'I-click ang card para baliktarin at makita ang layout ng benepisyo',
    templateNote: 'Ito ang opisyal na digital ID template ng OSCA Valenzuela na may tunay na logo. Ipapakita ng aktwal na ID ang personal na impormasyon ng senior.',
    digitalIdPreview: 'Preview ng Digital ID',
    invalidateThisId: 'I-invalidate ang ID na ito',
    statActiveIds: 'Aktibong ID',
    statInvalidated: 'Na-invalidate',
    statTotalIssued: 'Kabuuang Inilabas',
    readyForReleaseSection: 'Mga Na-verify na Senior, Handa na para sa Paglabas ng Digital ID',
    noSeniorsReady: 'Walang na-verify na senior na naghihintay ng digital ID sa ngayon.',
    verifiedLabel: 'Na-verify',
    releaseDigitalId: 'Ilabas ang Digital ID',
    searchByNameOrControl: 'Maghanap gamit ang pangalan o control number…',
    activeDigitalIds: 'Aktibong mga Digital ID',
    invalidatedIds: 'Mga Na-invalidate na ID',
    ctrlNo: 'Ctrl No.',
    releasedLabel: 'Nailabas',
    invalidatedLabel: 'Na-invalidate',
    noDigitalIdsYet: 'Wala pang inilabas na digital ID',
    digitalIdNoLinkedAccount: 'Walang naka-link na account ang record na ito, hindi maaaring ilabas.',
    digitalIdReleasedFor: 'Nailabas ang Digital ID para kay',
    digitalIdReleaseFailed: 'Nabigong ilabas ang digital ID. Pakisubukan muli.',
    invalidateConfirm: 'I-invalidate ang digital ID para kay',
    invalidateConfirmSuffix: 'Ito ay tatatakan bilang rebokado.',
    digitalIdInvalidatedFor: 'Ang Digital ID para kay',
    digitalIdInvalidatedSuffix: 'ay na-invalidate na.',
  },
};

const LangContext = createContext({ lang: 'en', t: LANGUAGES.en, setLang: () => {} });

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const stored = localStorage.getItem('scia_lang');
      // Migrate anyone previously on the removed Cebuano option back to English.
      return stored && LANGUAGES[stored] ? stored : 'en';
    } catch { return 'en'; }
  });

  const setLang = (code) => {
    if (!LANGUAGES[code]) return;
    setLangState(code);
    try { localStorage.setItem('scia_lang', code); } catch {}
  };

  const t = LANGUAGES[lang] || LANGUAGES.en;

  return (
    <LangContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export default LangContext;
